#!/usr/bin/env python3
"""
build_data.py -- regenerate the embedded data block of index.html
from the live ssc-mirror repository.

Run manually:      python3 build_data.py [path/to/index.html]
Run by CI daily:   see .github/workflows/site.yml
What it rewrites (everything between @@DATA-START@@ and @@DATA-END@@):
  BUILD_STAMP    today's date (UTC)
  LAST_SNAPSHOT  newest date tag on the mirror
  MISSING        dates with no tag since DAILY_START (computed, not assumed)
  INCLUDES       tags older than DAILY_START
  PACKAGES       every package name in the mirror's `releases` branch,
                 harvested from the per-letter stata.toc files

Uses `git ls-remote --tags` for the tag list (no API, no rate limits)
and raw.githubusercontent.com for the package tocs (no rate limits).
Exits 0 with "unchanged" if the block is already current, so a CI job
can skip the commit step.
"""
import datetime as dt
import re
import string
import subprocess
import sys
import time
import urllib.request

MIRROR_GIT = "https://github.com/labordynamicsinstitute/ssc-mirror.git"
MIRROR_RAW = "https://raw.githubusercontent.com/labordynamicsinstitute/ssc-mirror"
DAILY_START = dt.date(2021, 12, 21)
DATE_TAG = re.compile(r"^\d{4}-\d{2}-\d{2}$")
MARK_A, MARK_B = "/* @@DATA-START@@", "/* @@DATA-END@@ */"


def snapshot_tags() -> list[dt.date]:
    out = subprocess.run(["git", "ls-remote", "--tags", MIRROR_GIT],
                         check=True, capture_output=True, text=True).stdout
    tags = set()
    for line in out.splitlines():
        ref = line.split("refs/tags/")[-1].removesuffix("^{}")
        if DATE_TAG.match(ref):
            tags.add(dt.date.fromisoformat(ref))
    return sorted(tags)


def package_names() -> list[str]:
    names = set()
    for letter in string.ascii_lowercase + "_":
        url = f"{MIRROR_RAW}/releases/fmwww.bc.edu/repec/bocode/{letter}/stata.toc"
        try:
            with urllib.request.urlopen(url, timeout=30) as fh:
                text = fh.read().decode("utf-8", "replace")
        except Exception as exc:                       # letter dir may not exist
            print(f"  warning: {letter}/stata.toc skipped ({exc})", file=sys.stderr)
            continue
        for line in text.splitlines():
            parts = line.split()
            if len(parts) >= 2 and parts[0] == "p":
                names.add(parts[1].lower())
    return sorted(names)


def js_list(items) -> str:
    return "[" + ",".join(f'"{i}"' for i in items) + "]"


def main() -> int:
    path = sys.argv[1] if len(sys.argv) > 1 else "index.html"
    t0 = time.time()

    tags = snapshot_tags()
    last = max(tags)
    includes = [t for t in tags if t < DAILY_START]
    have = set(tags)
    missing, d = [], DAILY_START
    while d <= last:
        if d not in have:
            missing.append(d)
        d += dt.timedelta(days=1)
    pkgs = package_names()
    elapsed = time.time() - t0
    print(f"fetched {len(tags)} snapshot tags and {len(pkgs)} package names "
          f"in {elapsed:.1f}s")

    block = f"""{MARK_A} -- regenerated by build_data.py; do not edit by hand */
const BUILD_STAMP   = "{dt.date.today().isoformat()}";
const DAILY_START   = "{DAILY_START.isoformat()}";
let   LAST_SNAPSHOT = "{last.isoformat()}";
const MISSING  = {js_list(str(m) for m in missing)};
const INCLUDES = {js_list(str(i) for i in includes)};
const PACKAGES = {js_list(pkgs)};
{MARK_B}"""

    html = open(path, encoding="utf-8").read()
    a, b = html.find(MARK_A), html.find(MARK_B)
    if a < 0 or b < 0:
        print(f"error: data markers not found in {path}", file=sys.stderr)
        return 1
    new_html = html[:a] + block + html[b + len(MARK_B):]

    # ignore the daily BUILD_STAMP churn when deciding whether data changed
    strip = lambda s: re.sub(r'const BUILD_STAMP   = "[^"]*";', "", s)
    if strip(new_html) == strip(html):
        print("unchanged: mirror data identical to embedded data")
        return 0
    open(path, "w", encoding="utf-8").write(new_html)
    print(f"updated {path}: last snapshot {last}, "
          f"{len(missing)} missing dates, {len(pkgs)} packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
